### ISSUE TITLE
Feature Request: Smart Node Rescue Provider Opt-In

### ISSUE THREAD

**Issue by risasoft** [Rocket-Rescue-Node/rescue-proxy#35]
Would it be possible to integrate this into an add on to the smart node stack to allow any node operator to offer their node as a rescue node?

This could give the ability for any NO to opt into being a rescue node and combine that with fallback for other NOs. Somebody's node goes offline, then it would fallback to a pool of rescue nodes, chosen randomly.

Potential Issues:
How do we prevent MEV theft by provider?
What are the trust assumptions and how to minimize them?
How to incentivize NOs to offer their nodes as rescue?
Would this require smoothie pool opt-in by both parties as well?

**Comment by jshufro** [comment]
I'm going to close this- without answer to the question
> How do we prevent MEV theft by provider?
I am disinclined to make it too easy to run rescue-proxy and honeypot node operators
